name: Continuous Integration
on:
pull_request:
  branches:
    - main # ou qualquer outra branch

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
      - uses: actions/upload-artifact@v4
        with:
          name: projeto.zip
          path: |
            '**.py'
            README.md

  deploy:
    runs-on: ubunto-latest            
    need: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: projeto.zip
      - name: Display structure of downloaded files
        run: ls -R
