name: Continuous Delivery

on:
  pull_request:
    branches:
      - main 

jobs:
  deliver:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando o Continuous Delivery
        run: echo "Simulando CD"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: projeto
          path: |
            '**.py'
            README.md

  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: projeto

      - name: Display structure of downloaded files
        run: ls -R